WilsonCollantesAponte/Autopart-Express

- .gitignore
- package-lock.json
- package.json
- prisma/schema.prisma
> Wilson collantes aponte

- .env
- .gitignore
- package.json
- prisma/index.js
- prisma/schema.prisma
Se agregó el objeto "DatabaseInteraction" como instancia de PrismaCient, para poder interactuar con la base de datos
> Interacción con la base de datos

- app/product/form/api/route.js
- app/product/form/page.jsx
- package.json
V11 - End point - Form - nuevo respuesto
> V11 - End point - Form - nuevo respuesto

- .env
- package-lock.json
- package.json
- prisma/schema.prisma
V16 - model update - Databaase
> V16 - model update - Database

- app/client/form/login/page.jsx
- app/client/form/signIn/api/route.js
- app/dashboard/clients/page.jsx
- app/dashboard/products/page.jsx
- app/product/form/page.jsx
> V18 - Dashboard

- app/dashboard/clients/api/route.js
V19 - Newclient & delete user and relations
> V19 - Newclient & delete user and relations

- app/client/form/signIn/api/route.js
- app/dashboard/clients/api/route.js
- prisma/schema.prisma
> V20 - GET - PUT

- .env
- .gitignore
- app/client/form/login/api/name/route.js
- app/client/form/login/api/route.js
- app/dashboard/clients/api/route.js
- app/dashboard/products/api/route.js
- package-lock.json
- package.json
- prisma/index.js
- prisma/schema.prisma
> From Master

- app/Providers.js
- app/api/auth/[...nextauth]/route.js
- app/client/form/login/page.jsx
- app/client/form/nav/page.jsx
- app/client/form/signIn/page.js
- app/layout.js
- package-lock.json
- package.json
> Auth Google

- app/home/page.jsx
- package-lock.json
- package.json
V40 - Filters and their loading and error states
> V40 - Filters and their loading and error states

- app/home/page.jsx
> V45 - Pagination

- app/dashboard/products/components/ProductForm.jsx
actualizado a la nueva version de las tablas de Base de Datos.
> Formulario de productos 

- app/client/form/nav/page.jsx
- app/dashboard/clients/api/route.js
- app/dashboard/clients/clientRow.jsx
- app/dashboard/clients/page.jsx
- app/dashboard/clients/validations.js
- app/dashboard/layout.jsx
- app/layout.js
V56 - Dashboard products - logical erase
> V56 - Dashboard products - logical erase

- app/client/form/login/page.jsx
- app/dashboard/products/components/ProductForm.jsx
- app/dashboard/products/form/page.jsx
- components/Footer.jsx
estilos formulario crear producto
> estilos formulario crear producto

- app/client/form/login/api/email/route.js
- app/client/form/login/page.jsx
- app/client/form/signIn/page.jsx
Algunas mejoras y bug fix. Estaria bueno ver que dice el deploy.
> fix register y login

- app/dashboard/clients/clientRow.jsx
> V67 - Dashboard clients

- app/dashboard/clients/clientRow.jsx
- app/dashboard/clients/page.jsx
> V68 - Loading state

- app/dashboard/clients/clientRow.jsx
> V69 - Dashboard clients

- app/home/page.jsx
> Filtros-orden precio-estilos

- app/client/form/nav/page.jsx
- app/client/form/signIn/page.jsx
- app/dashboard/layout.jsx
- app/dashboard/products/clientRow.jsx
- app/dashboard/products/page.jsx
- app/dashboard/products/validations.js
> V70 - SignIn Google

- app/dashboard/products/api/route.js
- app/dashboard/products/page.jsx
- app/dashboard/products/productRow.jsx
- app/dashboard/products/validations.js
- prisma/schema.prisma
> V71 - Dashboard products

- app/client/form/login/page.jsx
- app/client/form/nav/page.jsx
- app/client/form/signIn/page.jsx
> V72 - SignIn / Login

- app/client/form/nav/page.jsx
> V82 - SignIn, Login

- app/client/form/login/page.jsx
- app/client/form/nav/page.jsx
> V86 - Signin, Login -

- app/cart/page.jsx
- app/home/addToCartButton.jsx
- app/home/page.jsx
V91 - Carrito - Validaciones - Endpoits
> V91 - Carrito - Validaciones - Endpoits

- app/home/page.jsx
- components/Footer.jsx
> filtro rating y filtro precio

- app/dashboard/products/components/ProductForm.jsx
Agregue input para agregar descripcion del producto, que el formulario se reinicie al hacer submit para seguir agregando productos y estilos para ver un preview de como se vera el producto en la pagina principal.
> Formulario productos Fix

- app/home/addToCartButton.jsx
- app/home/page.jsx
> V92 - cart

- app/home/addToCartButton.jsx
- app/home/page.jsx
> V93 - cart

- app/placeOrder/checkout/route.js
- app/placeOrder/notify/route.js
- app/placeOrder/page.jsx
- package-lock.json
- package.json
pase a la version 1.5.7 de mercadolibre y  use los datos de respuesta para borrar los productos comprados de BD
>  borra products comprados

- app/home/addToCartButton.jsx
- app/home/page.jsx
> V94 - fixing cart

- app/home/page.jsx
> V95 - Fixing cart

- app/client/form/login/page.jsx
- app/client/form/signIn/page.jsx
- app/home/addToCartButton.jsx
- app/home/page.jsx
- app/placeOrder/notify/route.js
> V96 - fixing cart

- app/page.jsx
> V98 - Fixing cart

- app/dashboard/products/api/route.js
- app/home/addToCartButton.jsx
- app/home/page.jsx
> V99 - Updating cart

- app/home/addToCartButton.jsx
- app/home/api/route.js
> V101 - Updating Cart

- app/home/addToCartButton.jsx
> V102 - Updating Cart

- app/cart/page.jsx
> V103 - Updating Cart

- app/cart/page.jsx
> V104 - Updating Cart

- app/home/page.jsx
> V105 - Updating Cart

- app/client/form/login/api/email/route.js
- app/client/form/login/page.jsx
- app/client/form/nav/page.jsx
> V106 - Logical deletion

- app/dashboard/products/components/ProductForm.jsx
- Cambio al tipo de datos de los inputs de Precio y disponibilidad para que no acepten letras. solo numeros.
- Cambio a la Funcion "onSubmit" para que no convierta los datos de Precio y Disponibilidad a Integers, ya que la base de datos acepta solo Strings.
> Cambios formulario de Productos

- app/client/form/nav/page.jsx
> V106 - Fix logical deletion

- app/home/page.jsx
> V107 - Home

- app/client/form/login/page.jsx
V108 - Fixing logical deletion
> V108 - Fixing logical deletion

- app/client/form/login/page.jsx
V108 - Fixing logical deletion - login
> V108 - Fixing logical deletion - login

- app/client/form/login/page.jsx
V109 - Fixing logical deletion - Login v2
> V109 - Fixing logical deletion - Login v2

- app/placeOrder/checkout/route.js
- app/placeOrder/failure/page.jsx
- app/placeOrder/notify/route.js
- app/placeOrder/pending/page.jsx
- app/placeOrder/status/page.jsx
> descontarcompra

- app/client/form/login/page.jsx
V112 - Fixing logical deletion - Login
> V112 - Fixing logical deletion - Login

- app/client/form/login/page.jsx
V113 - Fixing logical deletion - Login
> V113 - Fixing logical deletion - Login

- app/dashboard/products/components/ProductForm.jsx
Validaciones para etiquetas model, brand, price, availability e image.
Bloqueado el boton de submit hasta que no hayan errores en el formulario.
Animacion de carga de imagen para que el usuario sepa que se esta subiendo la imagen.
Animacion de loading al hacer submit del formulario.
> Validaciones formulario productos

- app/client/form/nav/page.jsx
> V114 - Cards - Home

- app/cart/page.jsx
- app/detail/[id]/page.jsx
- app/detail/componente/Botonmercado.jsx
> carrito comprar

- app/dashboard/products/components/ProductForm.jsx
Actualizacion de la ruta POST del formulario de productos de http://localhost:3000/dashboard/products/api  a  "autopart-express.vercel.app/dashboard/products/api"
> actualizacion de ruta POST formulario productos

- app/home/addToCartButton.jsx
- app/home/page.jsx
estilos cards y filtro precio usd
> estilos cards y filtro precio usd

- app/client/form/nav/page.jsx
- app/client/form/perfil/page.jsx
- app/client/form/profile/page.jsx
Agreugue componente perfil. Le falta mucho estilos
> Aguborio + perfil

- app/cart/api/route.js
- app/cart/many/route.js
- app/cart/page.jsx
- app/dashboard/products/api/route.js
- app/detail/[id]/page.jsx
- app/detail/componente/Botonmercado.jsx
- app/home/addToCartButton.jsx
- app/home/page.jsx
- app/placeOrder/checkout/route.js
- app/placeOrder/notify/route.js
- app/placeOrder/status/page.jsx
- prisma/schema.prisma
> Wilson21 maxi25

- app/cart/api/route.js
- app/cart/many/route.js
- app/cart/page.jsx
- app/dashboard/products/api/route.js
- app/detail/[id]/page.jsx
- app/detail/componente/Botonmercado.jsx
- app/home/addToCartButton.jsx
- app/home/page.jsx
- app/placeOrder/checkout/route.js
- app/placeOrder/notify/route.js
- app/placeOrder/status/page.jsx
- prisma/schema.prisma
> Wilson 20 maxi25

- app/cart/many/route.js
- app/cart/page.jsx
- app/detail/[id]/page.jsx
- app/detail/componente/Botonmercado.jsx
- app/placeOrder/checkout/route.js
- app/placeOrder/status/page.jsx
correcccion de la compra unica solo guarda una vaz , validacion en el post . detalles y validaciones con el boton de compra tanto carrito como compra unica
> correccion compraUnica

- app/detail/[id]/api/route.js
- app/detail/[id]/page.jsx
- app/detail/componente/Botonmercado.jsx
- prisma/schema.prisma
> V136 - reviews

- app/cart/many/route.js
- app/placeOrder/checkout/route.js
- app/placeOrder/status/page.jsx
- prisma/schema.prisma
> fecha y hora

- app/dashboard/clients/facturacion/route.js
- app/home/addToCartButton.jsx
- app/home/api/route.js
- app/home/page.jsx
> Wilson to merge others v2

- app/dashboard/carts/api/route.js
> Wilson dev merge v3

- app/home/addToCartButton.jsx
- app/home/api/route.js
- app/home/page.jsx
- app/placeOrder/checkout/route.js
correccion de un satus en home/api que no debia, interferia con el carrito
> status incorrecto mensaje filtros

- app/client/form/login/page.jsx
- app/client/form/profile/lastPur/page.jsx
- app/client/form/profile/page.jsx
- app/dashboard/clients/facturacion/route.js
A lo que hice le falta mucho estilos. Hay que ver como quieren hacer lo de los detalles de la compra, si quieren que genere otro componente para que cuando vaya a todas sus compras, solo vea un ID y un botton que lo direccione a el detalle de ese ID.
> perfil+productoscomprados

- app/detail/[id]/page.jsx
- app/detail/api/route.js
- app/detail/componente/oneComment.jsx
- package-lock.json
- package.json
- prisma/schema.prisma
> V150 - reviews - comments

- app/client/form/nav/page.jsx
- app/client/form/profile/page.jsx
- app/client/form/signIn/page.jsx
- app/dashboard/products/components/ProductForm.jsx
- app/dashboard/products/form/page.jsx
- app/home/page.jsx
> estilos perfil de usuario

- app/client/form/nav/page.jsx
> V156 - addCartButton

- app/client/form/nav/page.jsx
> V157 - fixing Cart

- app/client/form/login/page.jsx
- app/client/form/nav/page.jsx
ya esta la cuenta admin.
lacuenta para probarlo es admin@admin pw adminadmin
hay que ver el tema de inicio de sesion y register, de ponerlo en ingles tambien.
> Aguborio perfi

- app/cart/page.jsx
- app/client/form/login/page.jsx
- app/client/form/nav/page.jsx
- app/client/form/profile/lastPur/page.jsx
- app/client/form/profile/page.jsx
- app/client/form/signIn/page.jsx
- app/dashboard/clients/page.jsx
- app/dashboard/layout.jsx
- app/dashboard/orders/page.jsx
- app/detail/[id]/page.jsx
- app/detail/componente/Botonmercado.jsx
- components/Footer.jsx
- components/Hero.jsx
> unificar palabras en español

- app/detail/componente/oneComment.jsx
- package-lock.json
- package.json
- prisma/schema.prisma
V180 - Optional relation with the reviews table
> V180 - Optional relation with the reviews table

- app/home/page.jsx
> botones carrito

- app/cart/many/route.js
- app/client/form/profile/lastPur/page.jsx
- app/home/page.jsx
- app/placeOrder/checkout/route.js
- app/placeOrder/status/page.jsx
> precio&totales

- app/dashboard/clients/api/route.js
- app/dashboard/clients/clientRow.jsx
- app/dashboard/clients/page.jsx
Este es el pull correcto. El anterior desestimar.
> dashboard con admin y corregido tema estilos
